# Generated by Django 6.0 on 2025-12-24 22:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_iyzico", "0002_add_payment_method_model"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="paymentmethod",
            new_name="iyzico_paym_user_id_91d79d_idx",
            old_name="iyzico_pm_user_act_idx",
        ),
        migrations.RenameIndex(
            model_name="paymentmethod",
            new_name="iyzico_paym_card_to_6f9cdb_idx",
            old_name="iyzico_pm_token_idx",
        ),
        migrations.RenameIndex(
            model_name="paymentmethod",
            new_name="iyzico_paym_expiry__e0c63d_idx",
            old_name="iyzico_pm_expiry_idx",
        ),
        migrations.RenameIndex(
            model_name="subscription",
            new_name="iyzico_subs_user_id_23b6ed_idx",
            old_name="iyzico_sub_user_st_idx",
        ),
        migrations.RenameIndex(
            model_name="subscription",
            new_name="iyzico_subs_status_4a0f9c_idx",
            old_name="iyzico_sub_status_idx",
        ),
        migrations.RenameIndex(
            model_name="subscription",
            new_name="iyzico_subs_plan_id_3b7c81_idx",
            old_name="iyzico_sub_plan_st_idx",
        ),
        migrations.RenameIndex(
            model_name="subscription",
            new_name="iyzico_subs_cancel__bf9633_idx",
            old_name="iyzico_sub_cancel_idx",
        ),
        migrations.RenameIndex(
            model_name="subscriptionpayment",
            new_name="iyzico_subs_subscri_28f321_idx",
            old_name="iyzico_subp_sub_sta_idx",
        ),
        migrations.RenameIndex(
            model_name="subscriptionpayment",
            new_name="iyzico_subs_period__b00936_idx",
            old_name="iyzico_subp_period_idx",
        ),
        migrations.RenameIndex(
            model_name="subscriptionpayment",
            new_name="iyzico_subs_attempt_d12219_idx",
            old_name="iyzico_subp_attempt_idx",
        ),
        migrations.RenameIndex(
            model_name="subscriptionplan",
            new_name="iyzico_subs_is_acti_cac30f_idx",
            old_name="iyzico_sub_is_acti_idx",
        ),
        migrations.RenameIndex(
            model_name="subscriptionplan",
            new_name="iyzico_subs_slug_88694b_idx",
            old_name="iyzico_sub_slug_idx",
        ),
        migrations.AlterField(
            model_name="subscriptionpayment",
            name="amount",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Payment amount (before installments)",
                max_digits=10,
                verbose_name="Amount",
            ),
        ),
        migrations.AlterField(
            model_name="subscriptionpayment",
            name="bin_number",
            field=models.CharField(
                blank=True,
                help_text="First 6 digits of card (Bank Identification Number)",
                max_length=6,
                null=True,
                verbose_name="BIN Number",
            ),
        ),
        migrations.AlterField(
            model_name="subscriptionpayment",
            name="buyer_email",
            field=models.EmailField(
                blank=True,
                help_text="Buyer's email address",
                max_length=255,
                null=True,
                verbose_name="Buyer Email",
            ),
        ),
        migrations.AlterField(
            model_name="subscriptionpayment",
            name="buyer_name",
            field=models.CharField(
                blank=True,
                help_text="Buyer's first name",
                max_length=255,
                null=True,
                verbose_name="Buyer Name",
            ),
        ),
        migrations.AlterField(
            model_name="subscriptionpayment",
            name="buyer_surname",
            field=models.CharField(
                blank=True,
                help_text="Buyer's last name",
                max_length=255,
                null=True,
                verbose_name="Buyer Surname",
            ),
        ),
        migrations.AlterField(
            model_name="subscriptionpayment",
            name="card_association",
            field=models.CharField(
                blank=True,
                help_text="Card association (e.g., VISA, MASTER_CARD, AMEX)",
                max_length=50,
                null=True,
                verbose_name="Card Association",
            ),
        ),
        migrations.AlterField(
            model_name="subscriptionpayment",
            name="card_bank_code",
            field=models.CharField(
                blank=True,
                help_text="Issuing bank code",
                max_length=50,
                null=True,
                verbose_name="Card Bank Code",
            ),
        ),
        migrations.AlterField(
            model_name="subscriptionpayment",
            name="card_bank_name",
            field=models.CharField(
                blank=True,
                help_text="Issuing bank name",
                max_length=100,
                null=True,
                verbose_name="Card Bank Name",
            ),
        ),
        migrations.AlterField(
            model_name="subscriptionpayment",
            name="card_family",
            field=models.CharField(
                blank=True,
                help_text="Card family/program (e.g., Bonus, Axess, Maximum)",
                max_length=50,
                null=True,
                verbose_name="Card Family",
            ),
        ),
        migrations.AlterField(
            model_name="subscriptionpayment",
            name="card_last_four_digits",
            field=models.CharField(
                blank=True,
                help_text="Last 4 digits of card number",
                max_length=4,
                null=True,
                verbose_name="Card Last 4 Digits",
            ),
        ),
        migrations.AlterField(
            model_name="subscriptionpayment",
            name="card_type",
            field=models.CharField(
                blank=True,
                help_text="Card type (e.g., CREDIT_CARD, DEBIT_CARD)",
                max_length=50,
                null=True,
                verbose_name="Card Type",
            ),
        ),
        migrations.AlterField(
            model_name="subscriptionpayment",
            name="conversation_id",
            field=models.CharField(
                db_index=True,
                help_text="Unique conversation ID for tracking this payment",
                max_length=255,
                verbose_name="Conversation ID",
            ),
        ),
        migrations.AlterField(
            model_name="subscriptionpayment",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="When this payment record was created",
                verbose_name="Created At",
            ),
        ),
        migrations.AlterField(
            model_name="subscriptionpayment",
            name="currency",
            field=models.CharField(
                default="TRY",
                help_text="Currency code (e.g., TRY, USD, EUR)",
                max_length=3,
                verbose_name="Currency",
            ),
        ),
        migrations.AlterField(
            model_name="subscriptionpayment",
            name="error_code",
            field=models.CharField(
                blank=True,
                help_text="Iyzico error code (if payment failed)",
                max_length=50,
                null=True,
                verbose_name="Error Code",
            ),
        ),
        migrations.AlterField(
            model_name="subscriptionpayment",
            name="error_group",
            field=models.CharField(
                blank=True,
                help_text="Iyzico error group (if payment failed)",
                max_length=50,
                null=True,
                verbose_name="Error Group",
            ),
        ),
        migrations.AlterField(
            model_name="subscriptionpayment",
            name="error_message",
            field=models.TextField(
                blank=True,
                help_text="Iyzico error message (if payment failed)",
                null=True,
                verbose_name="Error Message",
            ),
        ),
        migrations.AlterField(
            model_name="subscriptionpayment",
            name="installment",
            field=models.IntegerField(
                default=1,
                help_text="Number of installments (1 for single payment)",
                verbose_name="Installment",
            ),
        ),
        migrations.AlterField(
            model_name="subscriptionpayment",
            name="installment_rate",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Installment fee rate as percentage",
                max_digits=5,
                null=True,
                verbose_name="Installment Rate",
            ),
        ),
        migrations.AlterField(
            model_name="subscriptionpayment",
            name="locale",
            field=models.CharField(
                default="tr",
                help_text="Locale for the payment (e.g., tr, en)",
                max_length=5,
                verbose_name="Locale",
            ),
        ),
        migrations.AlterField(
            model_name="subscriptionpayment",
            name="monthly_installment_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Amount per month for installment payments",
                max_digits=10,
                null=True,
                verbose_name="Monthly Installment Amount",
            ),
        ),
        migrations.AlterField(
            model_name="subscriptionpayment",
            name="paid_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Actual amount paid (may differ with installments)",
                max_digits=10,
                null=True,
                verbose_name="Paid Amount",
            ),
        ),
        migrations.AlterField(
            model_name="subscriptionpayment",
            name="payment_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Iyzico payment ID (unique identifier from Iyzico)",
                max_length=255,
                null=True,
                unique=True,
                verbose_name="Payment ID",
            ),
        ),
        migrations.AlterField(
            model_name="subscriptionpayment",
            name="raw_response",
            field=models.JSONField(
                blank=True,
                help_text="Complete response from Iyzico API (for debugging and audit)",
                null=True,
                verbose_name="Raw Response",
            ),
        ),
        migrations.AlterField(
            model_name="subscriptionpayment",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("processing", "Processing"),
                    ("success", "Success"),
                    ("failed", "Failed"),
                    ("refund_pending", "Refund Pending"),
                    ("refunded", "Refunded"),
                    ("cancelled", "Cancelled"),
                ],
                db_index=True,
                default="pending",
                help_text="Current payment status",
                max_length=20,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="subscriptionpayment",
            name="total_with_installment",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Total amount including installment fees",
                max_digits=10,
                null=True,
                verbose_name="Total with Installment",
            ),
        ),
        migrations.AlterField(
            model_name="subscriptionpayment",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="When this payment record was last updated",
                verbose_name="Updated At",
            ),
        ),
        migrations.AlterField(
            model_name="subscriptionpayment",
            name="user",
            field=models.ForeignKey(
                help_text="User who made the payment",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="iyzico_subscription_payments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
